---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sainatip/public_html/
    - /bin/cp -R _site/assets $DEPLOYPATH
    - /bin/cp _site/404.html $DEPLOYPATH 
    - /bin/cp _site/CV.pdf $DEPLOYPATH 
    - /bin/cp _site/typing-strictness-draft.pdf $DEPLOYPATH 
    - /bin/cp _site/Effects_Lecture_Notes.pdf $DEPLOYPATH 
    - /bin/cp _site/favicon.png $DEPLOYPATH 
    - /bin/cp _site/index.html $DEPLOYPATH
    - /bin/cp _site/picture.png $DEPLOYPATH  